version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 5s
      interval: 5s
      retries: 5




volumes:
  todolist_data:
