version: "3.9"

services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    restart: always
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
    image: yellowcarrot/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    command: gunicorn todolist.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: "${DB_NAME}"
      DB_USER: "postgres"
      DB_PASSWORD: "${DB_PASSWORD}"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - django_static:/usr/src/app/django_static

  frontend:
    image: sermalenk/skypro-front:lesson-34
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/django_static

volumes:
  db_data:
  django_static:
